/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChegirmalarRouteImport } from './routes/chegirmalar'
import { Route as MenyuRouteImport } from './routes/menyu'
import { Route as SavatRouteImport } from './routes/savat'
import { Route as TaomIdRouteImport } from './routes/taom.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChegirmalarRoute = ChegirmalarRouteImport.update({
  id: '/chegirmalar',
  path: '/chegirmalar',
  getParentRoute: () => rootRouteImport,
} as any)
const MenyuRoute = MenyuRouteImport.update({
  id: '/menyu',
  path: '/menyu',
  getParentRoute: () => rootRouteImport,
} as any)
const SavatRoute = SavatRouteImport.update({
  id: '/savat',
  path: '/savat',
  getParentRoute: () => rootRouteImport,
} as any)
const TaomIdRoute = TaomIdRouteImport.update({
  id: '/taom/$id',
  path: '/taom/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/chegirmalar': typeof ChegirmalarRoute
  '/menyu': typeof MenyuRoute
  '/savat': typeof SavatRoute
  '/taom/$id': typeof TaomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/chegirmalar': typeof ChegirmalarRoute
  '/menyu': typeof MenyuRoute
  '/savat': typeof SavatRoute
  '/taom/$id': typeof TaomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/chegirmalar': typeof ChegirmalarRoute
  '/menyu': typeof MenyuRoute
  '/savat': typeof SavatRoute
  '/taom/$id': typeof TaomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/chegirmalar'
    | '/menyu'
    | '/savat'
    | '/taom/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/chegirmalar'
    | '/menyu'
    | '/savat'
    | '/taom/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/checkout'
    | '/chegirmalar'
    | '/menyu'
    | '/savat'
    | '/taom/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ChegirmalarRoute: typeof ChegirmalarRoute
  MenyuRoute: typeof MenyuRoute
  SavatRoute: typeof SavatRoute
  TaomIdRoute: typeof TaomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chegirmalar': {
      id: '/chegirmalar'
      path: '/chegirmalar'
      fullPath: '/chegirmalar'
      preLoaderRoute: typeof ChegirmalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menyu': {
      id: '/menyu'
      path: '/menyu'
      fullPath: '/menyu'
      preLoaderRoute: typeof MenyuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savat': {
      id: '/savat'
      path: '/savat'
      fullPath: '/savat'
      preLoaderRoute: typeof SavatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taom/$id': {
      id: '/taom/$id'
      path: '/taom/$id'
      fullPath: '/taom/$id'
      preLoaderRoute: typeof TaomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ChegirmalarRoute: ChegirmalarRoute,
  MenyuRoute: MenyuRoute,
  SavatRoute: SavatRoute,
  TaomIdRoute: TaomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
