/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenyuRouteImport } from './routes/menyu'
import { Route as SavatRouteImport } from './routes/savat'
import { Route as TaomIdRouteImport } from './routes/taom.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenyuRoute = MenyuRouteImport.update({
  id: '/menyu',
  path: '/menyu',
  getParentRoute: () => rootRouteImport,
} as any)
const SavatRoute = SavatRouteImport.update({
  id: '/savat',
  path: '/savat',
  getParentRoute: () => rootRouteImport,
} as any)
const TaomIdRoute = TaomIdRouteImport.update({
  id: '/taom/$id',
  path: '/taom/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menyu': typeof MenyuRoute
  '/savat': typeof SavatRoute
  '/taom/$id': typeof TaomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menyu': typeof MenyuRoute
  '/savat': typeof SavatRoute
  '/taom/$id': typeof TaomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menyu': typeof MenyuRoute
  '/savat': typeof SavatRoute
  '/taom/$id': typeof TaomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/menyu' | '/savat' | '/taom/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/menyu' | '/savat' | '/taom/$id'
  id: '__root__' | '/' | '/menyu' | '/savat' | '/taom/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenyuRoute: typeof MenyuRoute
  SavatRoute: typeof SavatRoute
  TaomIdRoute: typeof TaomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menyu': {
      id: '/menyu'
      path: '/menyu'
      fullPath: '/menyu'
      preLoaderRoute: typeof MenyuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savat': {
      id: '/savat'
      path: '/savat'
      fullPath: '/savat'
      preLoaderRoute: typeof SavatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taom/$id': {
      id: '/taom/$id'
      path: '/taom/$id'
      fullPath: '/taom/$id'
      preLoaderRoute: typeof TaomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenyuRoute: MenyuRoute,
  SavatRoute: SavatRoute,
  TaomIdRoute: TaomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
